In [1]:
# Importing necessary packages
import pandas as pd
import numpy as np

In [2]:
# Task 1: Convert a dataframe into a CSV file, excluding the row index
project = pd.DataFrame({
    "ID": ['A001', 'A002', 'A003', 'A004', 'A005', 'A002', 'A005', 'A003', 'A001', 'A003', 'A001', 'A004', 'A004', 'A005'], 
    "Project": ['Project 1', 'Project 2', 'Project 3', 'Project 4', 'Project 5', 'Project 6', 'Project 7', 'Project 8', 'Project 9', 'Project 10', 'Project 11', 'Project 12', 'Project 13', 'Project 14'], 
    "Cost": [1002000, 2000000, 4500000, 5500000, None, 680000, 400000, 350000, None, 300000, 2000000, 1000000, 3000000, 200000], 
    "Status": ['Finished', 'Ongoing', 'Finished', 'Ongoing', 'Finished', 'Failed', 'Finished', 'Failed', 'Ongoing', 'Finished', 'Failed', 
               'Ongoing', 'Finished', 'Finished']
})
project.to_csv("Project_Data.csv", index=False)

employee = pd.DataFrame({
    "ID": ['A001', 'A002', 'A003', 'A004', 'A005'], 
    "Name": ["John Alter", "Alice Luxumberg", "Tom Sebastine", "Nina Adgra", "Amy Johny"], 
    "Gender": ['M', 'F', 'M', 'F', 'F'], 
    "City": ["Paris", "London", "Berlin", "Newyork", "Madrid"], 
    "Age": [25, 27, 29, 31, 30]
})
employee.to_csv("Employee_Data.csv", index=False)

seniority_level = pd.DataFrame({
    "ID": ['A001', 'A002', 'A003', 'A004', 'A005'], 
    "Designation Level": [2, 2, 3, 2, 3]
})
seniority_level.to_csv("Seniority_Level_Data.csv", index=False)

In [3]:
# Task 2: Fill NAN values in the Cost column with the Running Sum Average
project =pd.read_csv("Project_Data.csv")
running_sum = 0
count = 0
for i in range(len(project)):
    if not pd.isna(project.iloc[i, 2]):
        running_sum += project.iloc[i, 2]
        count += 1
        avg = running_sum / count
    else:
        project.iloc[i, 2] = avg

# # built in functions
# cumulative_sum = project['Cost'].fillna(0).cumsum()
# cumulative_count = (~project['Cost'].isna()).cumsum()
# running_avg = cumulative_sum.div(cumulative_count)
# project['Cost'] = project['Cost'].fillna(running_avg)

project

      ID     Project          Cost    Status
0   A001   Project 1  1.002000e+06  Finished
1   A002   Project 2  2.000000e+06   Ongoing
2   A003   Project 3  4.500000e+06  Finished
3   A004   Project 4  5.500000e+06   Ongoing
4   A005   Project 5  3.250500e+06  Finished
5   A002   Project 6  6.800000e+05    Failed
6   A005   Project 7  4.000000e+05  Finished
7   A003   Project 8  3.500000e+05    Failed
8   A001   Project 9  2.061714e+06   Ongoing
9   A003  Project 10  3.000000e+05  Finished
10  A001  Project 11  2.000000e+06    Failed
11  A004  Project 12  1.000000e+06   Ongoing
12  A004  Project 13  3.000000e+06  Finished
13  A005  Project 14  2.000000e+05  Finished

In [4]:
# Task 3: Split Name into First and Last Name and drop the Name column
employee = pd.read_csv("Employee_Data.csv")
employee[['First Name', 'Last Name']] = employee['Name'].str.split(' ', expand=True)
employee = employee.drop(columns=['Name'])
employee

     ID Gender     City  Age First Name  Last Name
0  A001      M    Paris   25       John      Alter
1  A002      F   London   27      Alice  Luxumberg
2  A003      M   Berlin   29        Tom  Sebastine
3  A004      F  Newyork   31       Nina      Adgra
4  A005      F   Madrid   30        Amy      Johny

In [5]:
# Task 4: create a Final dataframe combining all three dataframes
seniority_level = pd.read_csv("Seniority_Level_Data.csv")
Final = pd.merge(pd.merge(project, employee, on='ID', how='left'), seniority_level, on='ID', how='left')
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sebastine,3
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sebastine,3
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sebastine,3
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3

In [6]:
# Task 5: Create a bonus column which would be 5% of the Cost if the Status is Finished
Final['bonus'] = np.where(Final['Status']=='Finished', Final['Cost']*0.05, 0)
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sebastine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,2,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sebastine,3,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sebastine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,2,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [7]:
# Task 6: Reduce the designation level by 1 if the Status is failed and drop all the records where designation is > 4
Final['Designation Level'] = np.where(Final['Status']=='Failed', Final['Designation Level']-1, Final['Designation Level'])
Final.drop(Final[Final['Designation Level']>4].index)
Final

,ID,Project,Cost,Status,Gender,City,Age,First Name,Last Name,Designation Level,bonus
0,A001,Project 1,1.002000e+06,Finished,M,Paris,25,John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,F,London,27,Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,M,Berlin,29,Tom,Sebastine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,F,Madrid,30,Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,F,London,27,Alice,Luxumberg,1,0.0
6,A005,Project 7,4.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,M,Berlin,29,Tom,Sebastine,2,0.0
8,A001,Project 9,2.061714e+06,Ongoing,M,Paris,25,John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,M,Berlin,29,Tom,Sebastine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,M,Paris,25,John,Alter,1,0.0
11,A004,Project 12,1.000000e+06,Ongoing,F,Newyork,31,Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,F,Newyork,31,Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,F,Madrid,30,Amy,Johny,3,10000.0

In [8]:
# Task 7: Add courtesy titles in the First Name column and drop the gender column
Final["First Name"] = np.where(Final["Gender"]=="F", "Mrs. "+ Final['First Name'], "Mr. "+ Final['First Name'])
Final.drop(columns="Gender", inplace=True)
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sebastine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,3,162525.0
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,20000.0
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sebastine,2,0.0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sebastine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,1,0.0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,2,0.0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,2,150000.0
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,3,10000.0

In [9]:
# Task 8: Increase designation level by 1 if age is > 29 by using apply function
Final['Designation Level'] = Final.apply(lambda row: row['Designation Level']+1 if row['Age']>29 else row['Designation Level'], axis=1)
Final

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,bonus
0,A001,Project 1,1.002000e+06,Finished,Paris,25,Mr. John,Alter,2,50100.0
1,A002,Project 2,2.000000e+06,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
2,A003,Project 3,4.500000e+06,Finished,Berlin,29,Mr. Tom,Sebastine,3,225000.0
3,A004,Project 4,5.500000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
4,A005,Project 5,3.250500e+06,Finished,Madrid,30,Mrs. Amy,Johny,4,162525.0
5,A002,Project 6,6.800000e+05,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
6,A005,Project 7,4.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,4,20000.0
7,A003,Project 8,3.500000e+05,Failed,Berlin,29,Mr. Tom,Sebastine,2,0.0
8,A001,Project 9,2.061714e+06,Ongoing,Paris,25,Mr. John,Alter,2,0.0
9,A003,Project 10,3.000000e+05,Finished,Berlin,29,Mr. Tom,Sebastine,3,15000.0
10,A001,Project 11,2.000000e+06,Failed,Paris,25,Mr. John,Alter,1,0.0
11,A004,Project 12,1.000000e+06,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3.000000e+06,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0
13,A005,Project 14,2.000000e+05,Finished,Madrid,30,Mrs. Amy,Johny,4,10000.0

In [10]:
# Task 9: Calculate the total cost per employee by grouping records by employee id and first name
TotalProjCost = Final.groupby(['ID', 'First Name'], as_index=False)["Cost"].sum()
TotalProjCost.rename({"Cost": "Total Cost"}, axis=1, inplace=True)
TotalProjCost

     ID  First Name    Total Cost
0  A001    Mr. John  5.063714e+06
1  A002  Mrs. Alice  2.680000e+06
2  A003     Mr. Tom  5.150000e+06
3  A004   Mrs. Nina  9.500000e+06
4  A005    Mrs. Amy  3.850500e+06

In [11]:
# Task 10: Filter the records to include only cities whose name contain 'o'.
Final[Final["City"].str.contains("o", case=False)]

,ID,Project,Cost,Status,City,Age,First Name,Last Name,Designation Level,bonus
1,A002,Project 2,2000000.0,Ongoing,London,27,Mrs. Alice,Luxumberg,2,0.0
3,A004,Project 4,5500000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
5,A002,Project 6,680000.0,Failed,London,27,Mrs. Alice,Luxumberg,1,0.0
11,A004,Project 12,1000000.0,Ongoing,Newyork,31,Mrs. Nina,Adgra,3,0.0
12,A004,Project 13,3000000.0,Finished,Newyork,31,Mrs. Nina,Adgra,3,150000.0